service_name = "recommendations-api"
debug_mode = false

[rabbitmq]
url = "amqp://guest:guest@127.0.0.1/"
queue_name = "api_2_handler"

[[data_types]]
name = "pistachios"
area_size = [1, 3]

[[data_types]]
name = "clementines"
area_size = [3, 50]
